// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://kiwpkduqllcpwyqflclb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtpd3BrZHVxbGxjcHd5cWZsY2xiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY2OTM0ODEsImV4cCI6MjA4MjI2OTQ4MX0.to9bwRLTVCHtYjMRQClJQt-4M993jUj3ScuJeQOcfws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);